account/urls.py
from django.urls import path
from account import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'account'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('crm/', include('crm.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/urls.py
from django.urls import path
from crm import views

app_name = 'crm'

urlpatterns = [
    path('company_create/', views.CreateCompanyView.as_view(), name='cp-create'),
    path('company_list/', views.ListCompanyView.as_view(), name='cp-list'),
    path('company_delete/<int:pk>/', views.DeleteCompanyView.as_view(), name='cp-delete'),
    path('division_create/', views.CreateDivisionView.as_view(), name='dv-create'),
    path('division_detail/<int:pk>/', views.DetailDivisionView.as_view(), name='dv-detail'),
    path('division_delete/<int:pk>/', views.DeleteDivisionView.as_view(), name='dv-delete'),
    path('post_create/', views.CreatePostView.as_view(), name='ps-create'),
    path('post_list/', views.ListPostView.as_view(), name='ps-list'),
    path('employer_create/', views.CreateEmployerView.as_view(), name='ep-create'),
    path('employer_detail/<int:pk>/', views.DetailEmployerView.as_view(), name='ep-detail'),
    path('employer_list/', views.ListEmployerView.as_view(), name='ep-list'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--     favicon-->
    <link rel="shortcut icon" href="{% static 'book.ico' %}" />

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" defer></script>

    <!-- Dropzone js -->
    <link rel="stylesheet" href="{% static 'dropzone.css' %}">
    <script src="{% static 'dropzone.js' %}" defer></script>

    <!-- Custom js & css -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% block scripts %}
    {% endblock scripts %}

    <title>CRM app | {% block title %}{% endblock title %}</title>
</head>
<body>
{% include 'navbar.html' %}
<div class="container mt-3 mb-3">
    {% block content %}
    {% endblock content %}
</div>

 <!-- Bootstrap js -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"></script>
</body>
</html>

templates/navbar.html
{% load static %}
{% url 'account:signup' as path_to_signup %}
{% url 'account:login' as path_to_login %}
{% url 'account:logout' as logout %}
{% url 'account:profile' as path_to_my_profile %}
{% url 'crm:cp-create' as path_to_create_company %}
{% url 'crm:dv-create' as path_to_create_division %}
{% url 'crm:ps-create' as path_to_create_post %}
{% url 'crm:ep-create' as path_to_create_employer %}
{% url 'crm:cp-list' as path_to_list_company %}
{% url 'crm:ps-list' as path_to_list_post %}
{% url 'crm:ep-list' as path_to_list_employer %}


<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href=""><img src="{% static 'logo.png' %}" class="logo-sm"></a>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% if not request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link {% if request.path == path_to_signup %}active{% endif %}"
                       href="{{path_to_signup}}">Signup</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == path_to_login %}active{% endif %}"
                       href="{{path_to_login}}">Login</a>
                </li>
                {% else %}
                <div class="nav-item dropdown">
                    <div class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button"
                         data-bs-toggle="dropdown"
                         aria-expanded="false">
                        {{request.user}}
                    </div>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item {% if request.path == path_to_my_profile %}active{% endif %}"
                               href="{{path_to_my_profile}}">Profile</a></li>
                        <li><a class="dropdown-item" href="{{ logout }}">Logout</a></li>
                    </ul>
                </div>
                {% if request.user.is_superuser %}
                <li class="nav-item">
                    <a class="nav-link {% if request.path == path_to_create_company %}active{% endif %}"
                       href="{{path_to_create_company}}">Create Company</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == path_to_create_division %}active{% endif %}"
                       href="{{path_to_create_division}}">Create Division</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == path_to_create_post %}active{% endif %}"
                       href="{{path_to_create_post}}">Create Post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == path_to_create_employer %}active{% endif %}"
                       href="{{path_to_create_employer}}">Create Employer</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link {% if request.path == path_to_list_company %}active{% endif %}"
                       href="{{path_to_list_company}}">List Company</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == path_to_list_post %}active{% endif %}"
                       href="{{path_to_list_post}}">List Post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == path_to_list_employer %}active{% endif %}"
                       href="{{path_to_list_employer}}">List Employer</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>