config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('crm/', include('crm.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/urls.py
from django.urls import path
from crm import views

app_name = 'crm'

urlpatterns = [
    path('company_create/', views.CreateCompanyView.as_view(), name='cp-create'),
    path('company_list/', views.ListCompanyView.as_view(), name='cp-list'),
    path('company_delete/<int:pk>/', views.DeleteCompanyView.as_view(), name='cp-delete'),
    path('division_create/', views.CreateDivisionView.as_view(), name='dv-create'),
    path('division_detail/<int:pk>/', views.DetailDivisionView.as_view(), name='dv-detail'),
    path('division_delete/<int:pk>/', views.DeleteDivisionView.as_view(), name='dv-delete'),
    path('post_create/', views.CreatePostView.as_view(), name='ps-create'),
    path('post_list/', views.ListPostView.as_view(), name='ps-list'),
    path('employer_create/', views.CreateEmployerView.as_view(), name='ep-create'),
    path('employer_detail/<int:pk>/', views.DetailEmployerView.as_view(), name='ep-detail'),
    path('employer_list/', views.ListEmployerView.as_view(), name='ep-list'),
]

crm/models.py
from django.db import models
from account.models import Profile
from django.shortcuts import reverse
from datetime import date


class Company(models.Model):
    """
    Company's model
    """
    name = models.CharField(max_length=128)
    city = models.CharField(max_length=128)

    def __str__(self):
        return f'{self.name}'

    @property
    def list_divisions(self):
        return self.divisions.all()


class Division(models.Model):
    """
    Division's model
    """
    name = models.CharField(max_length=128)
    city = models.CharField(max_length=128)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='divisions')

    def __str__(self):
        return f'{self.company.name}: {self.name}'

    def get_absolute_url(self):
        return reverse('crm:dv-detail', kwargs={'pk': self.id})

    @property
    def list_post(self):
        return self.posts.all()


class Post(models.Model):
    """
    Post's model
    """
    name = models.CharField(max_length=128)
    division = models.ForeignKey(Division, on_delete=models.CASCADE, related_name='posts')
    salary = models.PositiveIntegerField()
    if_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.division.name} - {self.name}"


class Employer(models.Model):
    """
    Employer's model
    """
    worker = models.OneToOneField(Profile, on_delete=models.CASCADE, related_name='work')
    post = models.OneToOneField(Post, on_delete=models.CASCADE, related_name='employer')
    date_employment = models.DateField(auto_now_add=True)
    date_new_employment = models.DateField(auto_now=True)

    def __str__(self):
        return f"{self.worker.first_name} - {self.post.name}"

    @property
    def time_on_work(self):
        if not self.date_new_employment:
            return date.today() - self.date_employment
        else:
            return date.today() - self.date_new_employment

    def get_absolute_url(self):
        return reverse('crm:ep-detail', kwargs={'pk': self.id})

crm/forms.py
from django import forms
from crm import models


class CompanyForms(forms.ModelForm):
    """
    Company's form
    """
    class Meta:
        model = models.Company
        fields = '__all__'


class DivisionForms(forms.ModelForm):
    """
    Division's form
    """
    class Meta:
        model = models.Division
        fields = '__all__'


class PostForms(forms.ModelForm):
    """
    Post's form
    """
    class Meta:
        model = models.Post
        fields = '__all__'


class EmployerForms(forms.ModelForm):
    """
    Employer's form
    """
    class Meta:
        model = models.Employer
        fields = '__all__'

crm/views.py
from django.shortcuts import render
from django.views import generic
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from crm import forms
from crm import models
from crm import filters
from django.core.paginator import Paginator
from django.urls import reverse_lazy


class CreateCompanyView(LoginRequiredMixin, generic.CreateView):
    """
    View create company
    """
    form_class = forms.CompanyForms
    template_name = 'crm/create.html'
    success_url = '/crm/company_list/'
    login_url = '/account/login/'


class ListCompanyView(LoginRequiredMixin, generic.ListView):
    """
    View return lists of companies
    """
    login_url = '/account/login/'
    template_name = 'crm/company_list.html'
    queryset = models.Company.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.queryset
        filter = filters.CompanyFilter(self.request.GET, queryset)
        context["filter"] = filter
        return context


class DeleteCompanyView(LoginRequiredMixin, generic.DeleteView):
    """
    View for delete company
    """
    template_name = 'crm/delete.html'
    success_url = '/crm/company_list/'
    model = models.Company
    login_url = '/account/login/'


class CreateDivisionView(LoginRequiredMixin, generic.CreateView):
    """
    View create division
    """
    form_class = forms.DivisionForms
    template_name = 'crm/create.html'
    login_url = '/account/login/'

    def get_success_url(self):
        return reverse_lazy('crm:dv-detail', kwargs={'pk': self.object.pk})


class DetailDivisionView(LoginRequiredMixin, generic.DetailView, generic.UpdateView):
    """
    View for retrieve division
    """
    login_url = '/account/login/'
    template_name = 'crm/detail_division.html'
    context_object_name = 'division'
    form_class = forms.DivisionForms

    def get_success_url(self):
        return reverse_lazy('crm:dv-detail', kwargs={'pk': self.object.pk})

    def get_object(self, queryset=None):
        return get_object_or_404(models.Division, pk=self.kwargs.get('pk'))


class DeleteDivisionView(LoginRequiredMixin, generic.DeleteView):
    """
    View for delete division
    """
    template_name = 'crm/delete.html'
    success_url = '/crm/company_list/'
    model = models.Division
    login_url = '/account/login/'


class CreatePostView(LoginRequiredMixin, generic.CreateView):
    """
    View create post
    """
    form_class = forms.PostForms
    template_name = 'crm/create.html'
    login_url = '/account/login/'

    def get_success_url(self):
        return reverse_lazy('crm:dv-detail', kwargs={'pk': self.object.division.pk})


class ListPostView(LoginRequiredMixin, generic.ListView):
    """
    View return lists of posts
    """
    login_url = '/account/login/'
    template_name = 'crm/post_list.html'
    queryset = models.Post.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.queryset
        filter = filters.PostFilter(self.request.GET, queryset)
        context["filter"] = filter
        return context


class DeletePostView(LoginRequiredMixin, generic.DeleteView):
    """
    View for delete post
    """
    template_name = 'crm/delete.html'
    success_url = '/crm/company_list/'
    model = models.Post
    login_url = '/account/login/'


class CreateEmployerView(LoginRequiredMixin, generic.CreateView):
    """
    View create employer
    """
    form_class = forms.EmployerForms
    template_name = 'crm/create.html'
    login_url = '/account/login/'

    def get_success_url(self):
        return reverse_lazy('crm:ep-detail', kwargs={'pk': self.object.pk})


class DetailEmployerView(LoginRequiredMixin, generic.DetailView, generic.UpdateView):
    """
    View for retrieve employer
    """
    login_url = '/account/login/'
    template_name = 'crm/detail_employer.html'
    context_object_name = 'employer'
    form_class = forms.EmployerForms

    def get_success_url(self):
        return reverse_lazy('crm:ep-detail', kwargs={'pk': self.object.pk})

    def get_object(self, queryset=None):
        return get_object_or_404(models.Employer, pk=self.kwargs.get('pk'))


class ListEmployerView(LoginRequiredMixin, generic.ListView):
    """
    View return lists of employers
    """
    login_url = '/account/login/'
    template_name = 'crm/employer_list.html'
    queryset = models.Employer.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.queryset
        filter = filters.EmployerFilter(self.request.GET, queryset)
        context["filter"] = filter
        return context


class DeleteEmployerView(LoginRequiredMixin, generic.DeleteView):
    """
    View for delete employer
    """
    template_name = 'crm/delete.html'
    success_url = '/crm/company_list/'
    model = models.Employer
    login_url = '/account/login/'

templates/crm/company_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Companies
{% endblock title %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="card card-body">

            <form method="get">
                {{ filter.form.as_p }}

                <button class="btn btn-primary" type="submit">Search</button>
            </form>

        </div>
    </div>

</div>
<br>
<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <table class="table table-sm">
                <tr>
                    <th>Company</th>
                    <th>City</th>
                    <th>Divisions</th>

                    {% for filter in filter.qs %}
                <tr>
                    <td>{{filter.name}}</td>
                    <td>{{filter.city}}</td>
                    {% for division in filter.list_divisions %}

                    <td>
                        <a href="{{division.get_absolute_url}}"> {{division.name}}</a>
                    </td>

                    {% endfor %}
                </tr>
                <td>
                    {% if request.user.is_superuser %}
                    <a href="{% url 'crm:cp-delete' pk=filter.pk %}">Delete</a>
                    {% endif %}
                </td>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

{% endblock content %}

templates/crm/create.html
{% extends 'base.html' %}

{% block content %}
{% if request.user.is_superuser %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
</form>
{% endif %}
{% endblock content %}

templates/crm/delete.html
{% extends 'base.html' %}
{% block content %}
{%if request.user.is_superuser%}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>
{%endif%}
{% endblock %}

templates/crm/detail_division.html
{% extends 'base.html' %}
{% block content %}
{% block title %} {{division}} {% endblock title %}
<h1>Company: {{division.company.name}}</h1><br>
<h2>Company's division: {{division.name}}</h2><br>
<h2>Division's city: {{division.city}}</h2><br>
Posts in division:
{% for post in division.posts.all %}
<li>Position: {{post.name}} - ${{post.salary}}</li>
{% endfor %}
<br>
{% if request.user.is_superuser %}
<a href="{% url 'crm:dv-delete' pk=division.pk %}">Delete Division</a>
{% endif %}
{% endblock %}

templates/crm/detail_employer.html
{% extends "base.html" %}
{% block title %}

{% endblock title %}

{% block content %}
{{employer}}

{%if request.user.is_superuser%}
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn-primary mt-3">updated</button>
    <a href="{% url 'crm:cp-delete' pk=employer.pk %}">Delete</a>
    {% endif %}
</form>
{% endblock content %}

templates/crm/employer_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Companies
{% endblock title %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="card card-body">

            <form method="get">
                {{ filter.form.as_p }}

                <button class="btn btn-primary" type="submit">Search</button>
            </form>

        </div>
    </div>

</div>
<br>
<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <table class="table table-sm">
                <tr>
                    <th>Employer</th>
                    <th>Post</th>
                    <th>Come to work</th>
                    <th>Time on work</th>

                    {% for filter in filter.qs %}
                <tr>
                    <td>
                        <a href="{{filter.get_absolute_url}}">{{filter.worker.first_name}} {{filter.worker.second_name}}</a>
                    </td>
                    <td>{{filter.post}}</td>
                    {% if not filter.date_new_employment %}
                    <td>{{filter.date_employment}}</td>
                    {% else %}
                    <td>{{filter.date_new_employment}}</td>
                    {% endif %}
                    <td>{{filter.time_on_work}}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

{% endblock content %}

templates/crm/post_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Companies
{% endblock title %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="card card-body">

            <form method="get">
                {{ filter.form.as_p }}

                <button class="btn btn-primary" type="submit">Search</button>
            </form>

        </div>
    </div>

</div>
<br>
<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <table class="table table-sm">
                <tr>
                    <th>Post</th>
                    <th>Division</th>
                    <th>Salary</th>

                    {% for filter in filter.qs %}
                <tr>
                    <td>{{filter.name}}</td>
                    <td>
                        <a href="{{filter.division.get_absolute_url}}">{{filter.division}}</a>
                    </td>
                    <td>{{filter.salary}}</td>
                </tr>
                <td>
                    {% if request.user.is_superuser %}
                    <a href="{% url 'crm:cp-delete' pk=filter.pk %}">Delete</a>
                    {% endif %}
                </td>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

{% endblock content %}